### ISSUE TITLE
Injecting script-element created by Cash doesn't load

### ISSUE THREAD

**Issue by thasmo** [kenwheeler/cash#147]
This injects the script tag and loads/executes the script:

``` js
var s = document.createElement('script');
s.src = src;
parent.prepend(s);
```

This injects the script tag but doesn't load the script:

``` js
var s = $('<script/>').attr('src', src);
parent.prepend(s);
```

No idea why this doesn't work.

**Comment by shshaw** [comment]
Likely due to how elements are created in a `documentFragment`. I think this is the issue here: http://stackoverflow.com/questions/28112807/why-script-elements-created-through-domparser-do-not-execute

There may need to be an exception made for how `<script>` elements are created in the HTML parser.

**Comment by fabiospampinato** [comment]
If anybody wants to submit a PR for fixing this, that requires few bytes and it's fast, I'll be happy to consider it.

**Comment by fabiospampinato** [comment]
This is now supported https://github.com/kenwheeler/cash/commit/7fcf9bc57b94cc1dc4509e412d328a40d2c5cf54.

Except for the cases I mentioned earlier: script tags within iframes and script tags with a `src` attribute.
