### ISSUE TITLE
A question on design

### ISSUE THREAD

**Issue by softwarespot** [kenwheeler/cash#159]
Is there a reason for creating Init? I am basically curious, because surely you could do this instead ...

```
function cash(selector, context) {
    if (!(this instanceof cash)) {
        return new cash(selector, context);
    }

    // ... continue with querying the DOM etc...
}
```

**Comment by shshaw** [comment]
The original reason is probably "because jQuery does it", but the real reason is "performance".

The `instanceof` call slows the creation down by nearly 100% versus just returning a `new Init`. Try it for yourself with this simplified test:

https://jsperf.com/init-vs-instanceof

![screen shot 2017-01-13 at 9 55 16 am](https://cloud.githubusercontent.com/assets/777155/21936328/698a570e-d976-11e6-9c08-294d3db1d7fe.png)

Granted, you're probably not creating thousands of cash instances per second so the real world difference would not be drastic, however there's no advantage to the `instanceof` way other than somewhat simplifying the codebase. Filesize-wise, there's no significant difference between the two (a few bytes after minification) and the performance is so much greater that it's worth keeping Init.

If you think there's something I'm missing, please let me know.

**Comment by softwarespot** [comment]
Okay, so it was pre-optimisation. Thanks
