### ISSUE TITLE
Context not respected for getting elements by id

### ISSUE THREAD

**Issue by shashank-** [kenwheeler/cash#176]
In the case where context is another document (think of friendly iframes). 

In core.js on line 57 - 60 if the selector is that for an id, doc (rather than context) is explicitly used to find it and return.

**Comment by fabiospampinato** [comment]
I think we should fix this.

Right now contexts, as you pointed out, aren't used at all when searching by id (`#foo`), I think that was originally intended as a performance optimization actually.

**Comment by shshaw** [comment]
Yes, performance optimization and the fact that element IDs are supposed to be unique, never duplicated. This is also how jQuery handles ID selectors: https://api.jquery.com/id-selector/

**Comment by fabiospampinato** [comment]
I'll investigate this further, I'm not very familiar with using jQuery/cash with iframed pages.

I think if elements within an iframe can be selected by id from the parent page/scope without manually passing the `document` object then that's what anyone should do. If this isn't the case then I think we should support this.

**Comment by shshaw** [comment]
This is not something well supported, even in jQuery. iframe cross-talk isn't easy.
https://stackoverflow.com/questions/6316979/selecting-an-element-in-iframe-jquery

I'd personally classify this as an edge case but if it can be accomplished without adding numerous bytes or slowing down all ID selections then... ¯\_(ツ)_/¯

**Comment by shashank-** [comment]
@fabiospampinato To clarify, the use case which led me to find this was cash being loaded into a friendly-iframe and the document passed in belonged to the top window (Not the otherway around). 

@shshaw An alternate approach would be allow instances of cash that can be instantiated with a specific context (i.e. alternate documents)

**Comment by fabiospampinato** [comment]
An update on this:

- Turns out @shashank-'s use case was kind of already supported in previous versions of cash, you just had to write something like this: `$($('iframe)[0].contentDocument).find ( '#foo' )`

In jQuery you can achieve the same in 2 other ways:

- `$( '#foo', $('iframe').contents () )`: this is still not supported as it will slow down all the other, far more common, selections by id. Maybe we should still align cash with jQuery in this regard, I'm not sure, let's keep it this way for now.
- `$('iframe').contents ().find ( '#foo' )`: now this is supported too, I've implemented the `$.fn.contents` method in v2.3.0.

**Comment by fabiospampinato** [comment]
> $( '#foo', $('iframe').contents () ): this is still not supported as it will slow down all the other, far more common, selections by id. Maybe we should still align cash with jQuery in this regard, I'm not sure, let's keep it this way for now.

Turns out this can be implemented without sacrificing performance, so as of v.2.3.3 you can now do:

```js
$( '#foo', $('iframe').contents () )
```

This aligns cash with jQuery in this regard.
