### ISSUE TITLE
Supporting ES Module

### ISSUE THREAD

**Issue by asciian** [kenwheeler/cash#187]
Hello, there. Now we can use ES Module features in almost browsers.
You can make module of cash easily with adding  a line to the bottom of file.

```
...
export default $;
```

Could you support ES Module?

Thank you.

**Comment by fabiospampinato** [comment]
Thanks for your suggestion, I'll keep an eye on the popularity of the request.

Unfortunately adding support for this would be a bit trickier than what you propose, executing `export default $;` on browsers that don't support ES modules, but that cash still supports (IE10 and older versions of Firefox/Chrome etc.) will throw an error.

For the time being you'll be better off adding that line manually, or building cash yourself with a custom [wrapper](https://github.com/kenwheeler/cash/blob/cff93d00b22de61523c16bbed78c9ba8edb1f195/pacco.json#L18).

**Comment by asciian** [comment]
I agree that the wrapper is good for this issue. However, Vue.js provide three files vue.js vue.common.js and vue.esm.js for UMD/CommonJS/ES Module Users . This way is a solution for your problem.
I'll start to make `cash.esm.js` with the wrapper system.

If OFFICIAL project provide this file, it will be better than mine like the following.

- cash.min.js
- cash.esm.js
- cash.js

**Comment by timrosskamp** [comment]
I would also agree @asciian on creating a dedicated `cash.esm.js` file.

In the package.json file you can specify this file with the `module` and `jsnext:main` fields:

```json
{
    "main": "./dist/cash.js",
    "module": "./dist/cash.esm.js",
    "jsnext:main": "./dist/cash.esm.js"
}
```

When setting those fields in the package.json, module bundlers like webpack or rollup automatically recognise them and use the modern es module version of the libary instead, witch is a big advantage, especially for rollup.

**Comment by fabiospampinato** [comment]
> When setting those fields in the package.json, module bundlers like webpack or rollup automatically recognise them and use the modern es module version of the libary instead, witch is a big advantage, especially for rollup.

@timrosskamp  Didn't know that. Can you clarify on what advantages a bundler gains from using the ESM module?

**Comment by timrosskamp** [comment]
> Can you clarify on what advantages a bundler gains from using the ESM module?

When including a UMD or CommonJS Module into Rollup it needs to create an extra wrapper around it to get it to work in the bundled code. This adds extra overhead witch is unnecessary. Rollup is able to analyse the code and remove unused code (tree shaking), but this only works when importing es modules.

More information about this can be found on [this page](https://github.com/rollup/rollup/wiki/pkg.module) from the rollup wiki.

**Comment by fabiospampinato** [comment]
@timrosskamp Thanks for the explanation. I think the only advantage would be not needing the wrapper function around cash's code, we are only exporting one thing so there isn't anything to gain from tree-shaking.

Anyway this seems a requested enough feature, and it's easy to implement, so I'll do that as soon as I get the necessary free time.

**Comment by timrosskamp** [comment]
Accually, I just tested it (should have done that before) and it seems like rollup can't work with cash at all.

I get this error: `[!] Error: 'default' is not exported by node_modules\cash-dom\dist\cash.js`

This is caused because the bundle of cash doesn't export in any module format. Not even CommonJS or UMD.

**Comment by fabiospampinato** [comment]
If that'll be fixed with an ESM build that's one more reason to do it.

**Comment by fabiospampinato** [comment]
@artf this has nothing to do with partial builds, I've just simplified the wrapper around the module to simply export cash as `window.$ = window.cash = cash`.

> import $ from 'cash-dom'

Are you writing that in a Node.js environment? If so can you provide me with a little example of how you're using cash in node?

I've tried to require cash@1.3.7 in node via `require('cash-dom')` but I get a this error: `ReferenceError: document is not defined`. Maybe I need to load some other library that emulates a browser environment first? I'm not very familiar with this scenario.

**Comment by timrosskamp** [comment]
@fabiospampinato he is propably using a module bundler like webpack or rollup. Before version 2 cash.js was using the UMD pattern. With the current version, this libary is not exported in a module format that is compatible with a module bundler anymore. Because of that you can't use `import $ from 'cash'` anymore, because module bundler depend on AMD, requireJS or CommonJS module exports.

To fix this, we would need the dedicated `cash.esm.js` file, that exports in es module pattern or the main bundle would need to go back to UMD. Otherwise it's not possible to use this libary in a module bundler.

**Comment by fabiospampinato** [comment]
I see. I'm going to fix this later today or tomorrow 👌

**Comment by fabiospampinato** [comment]
Implemented in v2.1.7.

- We are now building also a `dist/cash.esm.js` file
- It isn't wrapped in an IIFE
- It doesn't pollute the global namespace
- I've added `module` and `jsnext:main` to `package.json`

I've tested it with rollup and it seems to be working for me.

Let me know if everything works as expected for you and/or if there's any change that should be made 😄

**Comment by hirako2000** [comment]
Could you show an example on how to import @fabiospampinato ?

**Comment by fabiospampinato** [comment]
@hirako2000 I've attached a sample webpack setup. I've never used Gatsby, I guess the process should be somewhat similar, I have to defer you to their docs for it.

[webpack_cash.zip](https://github.com/kenwheeler/cash/files/2049398/webpack_cash.zip)

**Comment by hirako2000** [comment]
Thanks @fabiospampinato for providing a sample project.
Interestingly it doesn't work for me. I had tried simply importing it like in this webapack_cash example.

Anyhow I then noticed it got injected to the window element. Not sure that was expected.
So this below worked for me:

```javascript```
require('cash-dom'); // or import $ from 'cash-dome';

window.$(element); //works.
```

**Comment by fabiospampinato** [comment]
@hirako2000 did you actually try the code I attached? My guess is that you're using an old version of WebPack (that doesn't support "jsnext:main" in `package.json`) and/or an old version of cash, since the ESM bundle doesn't pollute the global namespace.

**Comment by hirako2000** [comment]
Yes your sample project works.
I'm indeed using a pretty old version of webpack (transitively from gatsby).

Thanks for the tip, that would explain it. For now I will get along with leaving in the global scope, until we upgrade webpack.

**Comment by sntran** [comment]
I took a look at `dist/cash.esm.js` and it does not seem to `export default cash`. Only `exports["default"] = cash`.

This does not allow us to use cash in the browsers that support ES6 module, i.e.

```html
<script type="module">
import $ from "../node_modules/cash-dom/dist/cash.esm.js";
</script>
```

**Comment by StreetStrider** [comment]
@fabiospampinato, please, take a look at Rollup + rollup-plugin-sucrase when you'd have time :) It much more ES6/healthy way to bundle.

**Comment by fabiospampinato** [comment]
@StreetStrider we need our bundler to support file-level partial builds and optional imports, if you have another bundler in mind with this requisites, and you think that switching to it would be advantageous in some tangible way, I'd be happy to hear your suggestion.

**Comment by StreetStrider** [comment]
@fabiospampinato I'm not sure what bundler do you use? Initially, I thought that was the TS bundler, my recommendation was to use tsc with no-emit and Rollup + sucrase instead. But now I see you use some pacco bundler, then why you mention typescript compiler? (pacco use tsc under the hood?)
I think that for multi-targeting (ES6, CJS) Rollup is cool with possible some help from plugins (for instance, to ignore some stuff). I don't see [any partial builds in config](https://github.com/kenwheeler/cash/blob/bd76d9afbc6172f0f7cb1f3aa50f8a025be55714/pacco.json#L10-L20). If I'll understand your build I might help with some Rollup setup.

**Comment by fabiospampinato** [comment]
> I'm not sure what bundler do you use?

We use [pacco](https://github.com/fabiospampinato/pacco).

>  But now I see you use some pacco bundler, then why you mention typescript compiler? (pacco use tsc under the hood?)

Precisely, like any other bundler that compiles typescript after all.

>  I don't see any partial builds in config. 

You can just exclude paths via the "components" plugin included in pacco. https://github.com/kenwheeler/cash/blob/bd76d9afbc6172f0f7cb1f3aa50f8a025be55714/pacco.json#L3-L5

 It's not well documented though.

> If I'll understand your build I might help with some Rollup setup.

It's just a normal repo but instead of importing files with the `import` keyword we add directives for pacco that look like this: `// @require ./this/other/file.js`. If with Rollup you can have the same features that we have now, plus something else that's beneficial (otherwise it's not worth it), I'd be interested in talking more about that.

Keep in mind that we also need to output the smallest bundles possibles, maybe with some custom plugins you could bundle cash with webpack or something, but webpack in particular adds a bit of weight to the bundle, pacco basically just orders the files properly and concatenates them (at least in our current setup).

**Comment by fabiospampinato** [comment]
@sntran this is fixed in the latest build, `npm install cash@3.0.0-beta.3`. Let me know if you find any other problems.

**Comment by StreetStrider** [comment]
> We use pacco.

Understood. So pacco is more like include engine, similar to [rigger](https://www.npmjs.com/package/rigger) (it was a popular some days).
I understand why you use such approach, it's pretty reasonable because of jQuery is monolithic by its nature. So you conditionally include required modules, which, in turn instruments single jQuery-like instance. By controlling which modules to include one can control output bundle. It think that's reasonable, but I got ideas how to move this further which I'll try to explain in later comment, when I got time.

> like any other bundler that compiles typescript after all

Not any. I repeat that Rollup can do all ES6-modules-related stuff, sucrase is fast and simple tool to cut out all TS syntax, and you still can use very rich module infrastructure, including bridge to Babel if you really need to. TS can still check types with `--no-emit`. (the only possible minor issue here is to turn extensions `.ts` and `.js`).

> Keep in mind that we also need to output the smallest bundles possible

It'll be achieved by default due to tree-shaking. Note that because Rollup is ES6 modules bundler, it will not create additional compability wrappers, like CJS bundler, but instead it will try to avoid wrappers and keep code plain. You can test it in [playground](https://rollupjs.org/repl). It will not, though, work at 100% in jQuery-like case, cause of implicit references to all modules from jQuery instance. Tree-shaking still will work on per-module basis.

> You can just exclude paths via the "components" plugin included in pacco.

I think that ability to exclude modules can then be achieved by something like [rollup-plugin-ignore](https://www.npmjs.com/package/rollup-plugin-ignore).

**Comment by limonte** [comment]
Pika also confirms this: https://www.pikapkg.com/packages/?q=cash-dom

**Comment by fabiospampinato** [comment]
Yes, `cash-dom` not `cash`, sorry for the typo.
