### ISSUE TITLE
.empty() method is slow, could be 98% faster

### ISSUE THREAD

**Issue by limonte** [kenwheeler/cash#205]
Proof: https://jsperf.com/removechild-vs-cash/1

![image](https://user-images.githubusercontent.com/6059356/46398553-17e9ef00-c6fe-11e8-8aa9-bee0a273a4f2.png)

Reading: https://coderwall.com/p/nygghw/don-t-use-innerhtml-to-empty-dom-elements

Suggested change: instead of `html = ''` do `.removeChild()`

**Comment by fabiospampinato** [comment]
That's not an apple-to-apple comparison. In the first test you're also measuring everything that happens because of `$(box)`, in the second test you're not checking if `box` is undefined, which we are doing inside `cash.fn.empty`. Also `cash.fn.empty` works for multiple elements too, that adds a bit of overhead.

Revising the [test](https://jsperf.com/removechild-vs-cash-3) shows "only" a ~4x increment in performance, rather than 40x, which is still significant though.

**Comment by fabiospampinato** [comment]
This turned out to be much more complex than I expected:

- Cash's implementation uses `innerHTML`
- Zepto's implementation uses `innerHTML` too
- jQuery's implementation is much more convoluted:
  - For each element it retrieves all the elements below it
  - It removes any attached events to them
  - Instead of `innerHTML` it uses `textContent` which doesn't parse the passed string as HTML, so it's faster

I did some more [experimentation](https://jsperf.com/removechild-vs-cash-3), and I'm not sure what we should do here: 

- Being more compatible with jQuery will slow down the method (2x slower in Chrome, 4x slower in Firefox). 
- Not being more compatible with jQuery will cause some memory leaks if those removed elements have events attached to them.
- Merging your PR will speed up the method by 4x, but it won't remove text nodes (comments) that we are currently removing.
- We could replace `innerHTML` with `textContent` for a very marginal performance improvement, but we'll have to ship more bytes to the client (keeping cash small is one of the main goals of the project).

I would personally go either for just keeping everything as it is, or actually cleaning up events from removed elements, like jQuery's doing.

What do you think?
