### ISSUE TITLE
QUnit error messages are misleading

### ISSUE THREAD

**Issue by limonte** [kenwheeler/cash#217]
![image](https://user-images.githubusercontent.com/6059356/46921745-d1eb3000-d007-11e8-9db4-f891d99d2e07.png)

`height set Passed!` is the opposite of truth :) The same issue is for all tests.

`message` (3 parameter) is optional and could be dropped, it's needed only in cases when a short additional description of an assertion is required.

**Comment by fabiospampinato** [comment]
Yeah that's a legacy thing.

Since we are often performing multiple assertions inside each test unit I think it would be better to keep the messages, but `height set Passed!` is kind of weird as you pointed out.

Perhaps the entire test suite should be refactored? I'm not sure it's worth the time though.

I think all those messages should be reviewed, basically all those " Passed!" suffixes should be removed and the messages should be short and descriptive.

I'll be happy to consider a PR for this.

**Comment by fabiospampinato** [comment]
I've removed the " Passed!" suffix.

Feel free to open a separate issue/PR about refactoring the test suite.
