### ISSUE TITLE
v3 is no longer dependency-free?

### ISSUE THREAD

**Issue by limonte** [kenwheeler/cash#255]
I'm testing out v3 and having the unwanted `@types/node` dependency:

![image](https://user-images.githubusercontent.com/6059356/53702574-366d2700-3e11-11e9-8c49-438fa0ccbd87.png)

v2 is dependency-free: https://www.npmjs.com/package/cash-dom

v3 is not: https://www.npmjs.com/package/cash-dom/v/3.0.0-beta.3

![image](https://user-images.githubusercontent.com/6059356/53702627-9663cd80-3e11-11e9-8628-d68bf53fd3fa.png)

Is that by mistake or `@types/node` is now the required subdependency?

**Comment by fabiospampinato** [comment]
Under the `@types` namespace/user Typescript types are published.

I've ~recently moved those `@types/*` dependencies from `devDependencies` to `dependencies` across all the repositories I'm managing because sometimes when the typescript compiler is compiling the types declaration for a specific library it assumes that those types defined under those `@types/*` packages are available. If they are only available during development the compiled declaration might not work properly.

Now, many times there's no need to declare those packages as dependencies, but in order to avoid having to think about this every time I make a release I now usually put those `@types/*` packages under `dependencies`.

There's no actual code in there, so it won't be a problem for your bundles.

**Comment by limonte** [comment]
> Now, many times there's no need to declare those packages as dependencies, but in order to avoid having to think about this every time I make a release I now usually put those @types/* packages under dependencies.

1. The releasing process should be ideally automated and run from CI, not manually. Manual work is a bug.
2. Fixing your personal dev environment issues by the price of adding subdependencies to `cash` doesn't sound like a good idea.

Many devs seem to love "zero dependencies" or "dependency-free" packages:

![image](https://user-images.githubusercontent.com/6059356/53702900-95806b00-3e14-11e9-890d-3f4898b2eb95.png)

PS. the TS hype drives me crazy, people are sacrifying important things to have their small projects written in TS :/

**Comment by fabiospampinato** [comment]
> The releasing process should be ideally automated and run from CI, not manually. Manual work in this case is a bug.

I don't think that has nothing to do with this issue, and since https://github.com/kenwheeler/cash/commit/810d69bd5a12498a94e3dce5e171134f16cc5cb4 now the release process is automated.

> Fixing your personal dev environment issues by the price of adding subdependencies to cash doesn't sound like a good idea.

It's not about the dev environment, as this change won't change a thing in that scenario, the problem is that sometimes types are missing in the production bundle. I just don't want to think about when and which types are needed.

`@types/node` is only a dependency as far as npm is concerned, the `.js` version of cash v3 doesn't care about that at all.

Is it really a problem that a few more megabytes are being downloaded? As long as they are not included in the final bundle I don't see the problem.

> PS. the TS hype drives me crazy, people are sacrifying important things to have their small projects written in TS :/

I don't know about the hype, but TS is totally amazing IMHO, I wouldn't want to deal with a big-ish repository that doesn't have any sorts of types in it.

**Comment by limonte** [comment]
> Is it really a problem that a few more megabytes are being downloaded? 

It's 590Kb, but it's 590 of *completely useless for end users* kilobytes. The "this is fine" way of thinking is the direct reason for this meme:

![image](https://user-images.githubusercontent.com/6059356/53717902-44976380-3e62-11e9-9bad-e60fdf0fb7b8.png)

In order to understand me better, it would be good to travel to any developing country and experience the Internet connection there, especially mobile Internet connection. After that, you will probably appreciate every saved kilobyte :)

For SweetAlert2 we:
1. have Travis check to control the total number of dev-deps: https://github.com/sweetalert2/sweetalert2/pull/1313
2. working on replacing dev-deps with native code when possible: https://github.com/sweetalert2/sweetalert2/pull/1436

**Comment by fabiospampinato** [comment]
If you wanna take the time to check that the generated types don't actually need `@types/node` and want to submit a PR for moving that back to `devDependencies` be my guest.

**Comment by limonte** [comment]
I can't contribute to `cash` atm because I don't know TS.

That's another big thing you sacrificed for TS, previously all JS devs were able to contribute, now it's only for advanced developers, and I'm not on that level.
