### ISSUE TITLE
RFE: Implement missing `jQuery.end`

### ISSUE THREAD

**Issue by SamyCookie** [kenwheeler/cash#260]
### Feature description

Implement missing `jQuery.end` traversing method

### Feature motivation

Be more compatible with `jQuery`

Is this feature present in jQuery? Yes
https://api.jquery.com/end/

**Comment by fabiospampinato** [comment]
I don't think this method aligns well with our goal with being "absurdly small".

And personally I've never used it, and it seems kind of useless to me, they use it like this in the docs:

```js
$( "ul.first" )
  .find( ".foo" )
    .css( "background-color", "red" )
  .end()
  .find( ".bar" )
    .css( "background-color", "green" )
  .end();
```

IMHO it doesn't make sense to use `end`, just write it like this:

```js
const $ul = $( "ul.first" );

$ul.find( ".foo" ).css( "background-color", "red" )
$ul.find( ".bar" ).css( "background-color", "green" );
```

Using `$.fn.end` in order to avoiding creating a variable in order to avoid executing the same selector twice doesn't like a great tread-off to me.

**Comment by SamyCookie** [comment]
Fair enough ! Thanks for the answer.

Personally I have used it a lot in the past, but in fact I agree with your last statement.
It was mostly for jQuery retrocompatibility.
