### ISSUE TITLE
$.fn.append: support for appending plain text

### ISSUE THREAD

**Issue by peterbe** [kenwheeler/cash#275]
### Current behavior

This codepen reproduces it: https://codepen.io/peterbe/pen/WBwqLa?editors=1010#0
See Web Console. 

You get:
```
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': ', then copy the link to the search results together with your comment.' is not a valid selector.
```
...in Chrome. 
<img width="1770" alt="Screen Shot 2019-05-10 at 10 26 13 PM" src="https://user-images.githubusercontent.com/26739/57563963-a4cee800-7372-11e9-85b3-a1fc68a30ff4.png">

And...
```
SyntaxError: ', then copy the link to the search results together with your comment.' is not a valid selector
```
in Firefox Nightly. 
<img width="1017" alt="Screen Shot 2019-05-10 at 10 24 55 PM" src="https://user-images.githubusercontent.com/26739/57563958-94b70880-7372-11e9-8fba-e1a127d6b986.png">

### Expected behavior

That it doesn't crash.

**Comment by fabiospampinato** [comment]
It looks like this stems for a minor incompatibility between jQuery and Cash: jQuery doesn't support getting passed a selector in `$.fn.append`, Cash does. Since we do support selectors there we can't support appending plain text because the thing will be ambiguous in certain situations:

```js
$('.foo').append ( '.something' ) // Do we want to append ".something" as text or is that a selector?
```

The workaround would be to pass a node to Cash's `$.fn.append` function instead, basically you'll have to wrap your text in `document.creatTextNode` as shown here: https://codepen.io/FabioSpampinato/pen/qGNbJp?editors=1010

I think it would be better to maintain the current behavior, as it helps keeping the implementation very concise, I've personally never seen plain text appended this way so maybe it's not a very common use case, and aligning more with jQuery in this scenario will be a breaking change. I think instead the readme and migration guide should be updated.

@peterbe What do you think?

**Comment by peterbe** [comment]
I took some ancient code, written by a much younger me, an swapped out jQuery 3 for cash and waited to see what would happen. When I actually look at the code, I realize that it's kinda ugly. 

Do what you think is best. Perhaps cash doesn't pretend to be exactly compatible with jQuery. 

By the way, if I inject a `<span>` and `</span>` into the string, [it works](https://codepen.io/peterbe/pen/MdjEbj?editors=1010#0)

**Comment by fabiospampinato** [comment]
> By the way, if I inject a <span> and </span> into the string, it works

If cash detects that the string contains some HTML it tries to parse it, it's just that plain text notes aren't supported.
