### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by limonte** [kenwheeler/cash#288]
Code coverage is IMO the main metric of the project maintainability. 

For projects like this one code coverage >= 90 would make sense.

@fabiospampinato do you have any information on what's the current coverage?

**Comment by fabiospampinato** [comment]
> Code coverage is IMO the main metric of the project maintainability.

I think in general it depends on how much the tested APIs will change in the future 🤔 

> For projects like this one code coverage >= 90 would make sense.

I'm not a fan of 100% code coverage or anything like that, but our APIs are relatively stable so I guess it would make sense in general for a similar project to have more tests. But since we can run jQuery's test suite with cash I don't think it would be a particularly good use of our time to write more tests. Spending some time running jQuery's test suite with cash (`npm run test:jquery`), trying to find bugs, would probably be much more useful.

 > @fabiospampinato do you have any information on what's the current coverage?

No idea. I would say our test suite is fairly decent, but jQuery's is just massive (they have quite a few more methods to test though).

PRs that enhance our test coverage are welcome 👍
