### ISSUE TITLE
Issue with adding external library to TS in VS2017

### ISSUE THREAD

**Issue by zharonar** [kenwheeler/cash#293]
Greetings,

We are trying to implement type definision in our TS 3.0.1 in VS2017.

Our main goal is to reduce script usage to the max. Meaning switching from JQuery to something lighter, etc... and not using any module loader like webpack or extensions like requireJs... Otherwise this would be pointless.

**What we are trying to achieve is to get only referenced types so we can get intellisense in our TS file.**

We don't want to use `import Cash from '{path_to_definition}'` because it give us `define("module", ... ` which require some module loaders etc... 

Our code example:

`/// <reference path="../vendor/cash/cash.d.ts" />`
`var mapContainer: HTMLElement;`
`var Siema: any;`

`class webapp {`
`    static loading = function (selector: Cash) {`
`        selector.prop('disabled', true); `
`        selector.addClass('loading');  `
`    } `
 `   static reset = function (selector: Cash) {`
`        selector.prop('disabled', false); `
`        selector.removeClass('loading');`
 `   }`

The problem is that in our class, loading fn property `selector` can't find the type `Cash`.

We tried many other ways to solve this, we read all the issues and solutions to the problem, but none helped.

**Comment by fabiospampinato** [comment]
> We don't want to use import Cash from '{path_to_definition}' because it give us define("module", ... which require some module loaders etc...

I don't know exactly what you're building, but IMHO generally worrying about these sorts of things is a waste of time, meaning that usually, in my experience at least, a year from now the product will mostly likely be better overall if instead of worrying about squeezing out the very last kb all that energy were to be used for improving the product in some other way.

I think the issue here might be that cash isn't actually exporting any types, so you can't use for instance its internal "Selector" type in your app code. I hope to get this fixed in the next release.

Anyway I think what you need in the code you posted is the type of a cash instance, and you can get it this way, which is what I'm doing in a project of mine:

```ts
type Cash = ReturnType<typeof import ( 'cash-dom' ).default>;
```

It's not very ergonomic, but until this gets fixed properly it's a decent workaround, and it adding this type definition won't increase the size of your bundles.

**Comment by fabiospampinato** [comment]
You can now get the collection type via `import {Cash} from 'cash-dom';`, some other useful types are now exported too.
