### ISSUE TITLE
Property 'className' does not exist on type 'Ele'

### ISSUE THREAD

**Issue by limonte** [kenwheeler/cash#295]
Good day @fabiospampinato! I'm learning TS and here's the thing I'm not sure if it's a bug or not:

```js
import $ from 'cash-dom'

const a = $('body').get(0).className
```

produces

```
Property 'className' does not exist on type 'Ele'.
```

![image](https://user-images.githubusercontent.com/6059356/62409908-c4c71e00-b5e6-11e9-80cc-fe456b1e6083.png)

Is it supposed to work like that?

I would expect `$('body').get(0)` to be `HTMLElement`, but I guess that's the wrong expectation and I'm lacking some knowledge about TS.

**Comment by fabiospampinato** [comment]
I see multiple issues here, a few of them regarding your assumptions:

- First of all you're assuming that `$('body')` will always match the body element, I think that might not be the case as there might not be any `body` node in the DOM yet if for instance you're running that code synchronously from inside your `head` tag or if you are manually removing that node from the DOM for some reason.

- Secondly I don't think any type system is smart enough to figure out that if `$('body')` matches the `body` element than calling `.get(0)` will return it, for a couple of reasons:
	- Between the two function calls you could manually change the elements present in in the collection (e.g. `$collection[0] = window`), so the first element might no longer be `body`.
    - In this scenario TypeScript knows that a Cash collections contains an array of [`Ele`](https://github.com/kenwheeler/cash/blob/master/src%2Fcore%2Ftypes.ts/#L16)s, but when retrieving the first element of the collection it doesn't know what more specific type it has, it's just of type "Ele" as far as it's concerned, it might be the `window` object, it might be `HTMLElement` etc. and TypeScript is telling you that there are some possible branches where your code is accessing a property that doesn't exist.

Others regarding Cash:

- First of all it seems that the `$.fn.get` method is typed incorrectly, as it could also return `undefined` (e.g. `$collection.get ( 1000 )` might not even exist).

- Secondly while it's technically more strict/correct to say that `$.fn.get` will either return `undefined` or an `Ele` when called with an index, it's a pain the ass to always consider the case where the element in the collection might in the window object. I think it's very difficult to actually hit a bug where one has selected the window object my stake, so it's not worth it typing these methods so strictly. Because of this some methods are typed more loosely and will actually return the [`EleLoose`](https://github.com/kenwheeler/cash/blob/master/src%2Fcore%2Ftypes.ts/#L17) type, assuming you know what you're doing in this situation. It looks like the `$.fn.get` method, and a few others, should use this type too.

I'll try to address these last 2 issues today 👍

**Comment by limonte** [comment]
It's a pleasure to learn TS while reading your code and comments @fabiospampinato, thank you!

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next release.

Weirdly enough though I've hit what it seems to be a VSCode [bug](https://github.com/microsoft/vscode/issues/78495) where even though the types state correctly that `$.fn.get` could return `undefined` VSCode isn't recognizing that properly.
