### ISSUE TITLE
.data(name, val) converts to strings, loosing Object unlike jquery

### ISSUE THREAD

**Issue by adumesny** [kenwheeler/cash#306]
I'm looking at this lib to reduce Jquery load for https://github.com/gridstack/gridstack.js but find that .data() looses the object passed in to be stored *unlike jquery* - this breaks a lot of code!

sample code (works with jquery)
```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.js"></script>
<!-- <script src="../src/cash.js"></script> -->
<body>
  <button id="button">Add Widget</button>

  <script type="text/javascript">
    $(function () {
      var myObj = {first: 1, second: 2};
      $('#button').data('foo', myObj)
      myObj.third = 3;
      var myObj2 = $('#button').data('foo');
      console.log('should be 3 = ' + myObj2.third);
    });
  </script>
</body>
```
### Current behavior

returns undefined as
```
function data(name, value) {
...
if (isString(name)) {
    if (value === undefined) return this[0] && getData(this[0], name);
    return this.each(function (i, ele) {
      return setData(ele, name, value);
```
and
```
function setData(ele, key, value) {
  try {
    value = **JSON.stringify(value);**
  }
  if ( ele.dataset ) {
    ele.dataset[camelCase ( key )] = value;
  } else {
    ele.setAttribute ( `data-${key}`, value );
  }
```
setData() is always converting to a string and storing to dom fields, instead of caching the object

### Expected behavior
 
store and return the original data object, like Jquery (.third = 3 ouput)

**Comment by adumesny** [comment]
I'm using jquery 3.4.1 (latest) and not finding this to be the case (above examples update the stored object just fine on Chrome)

from your doc:

### Data caching

In jQuery the `$.fn.data` function caches retrieved values, and doesn't refresh them when they are updated outside of jQuery (e.g. via the `dataset` API), this makes jQuery's `$.fn.data` function unusable with libraries like React. Cash doesn't implement such caching functionality and doesn't have this problem, the retrieved values are always fresh.

Also values set via `$.fn.data` are stored as JSON values in `data-*` attributes set on the DOM nodes, so for instance calling `$('#foo').data ( 'test', 123 )` will add a `data-test="123"` attribute to the `#foo` node.
-----

I also see  this:

### Version 4.1.1
- Test: using setAttribute instead of the dataset API

**Comment by fabiospampinato** [comment]
> setData() is always converting to a string and storing to dom fields, instead of caching the object

This is intentional and mentioned in the migration guide.

> store and return the original data object, like Jquery (.third = 3 ouput)

jQuery's implementation has problems, which is why we aren't aligning with it on purpose, the crucial one being that if you're using it along with a DOM-diffing-based view library (like React) this scenario will probably arise eventually:

1. You have a DOM element with a `data-*` attribute.
2. You fetch that data attribute via jQuery.
3. The DOM element gets reused by the view library of your choice, so the actual node is the same, but its properties/attributes will be updated. This means the `data-*` attribute might get updated but the actual node will stay the same object as far as JS is concerned.
4. Fetching that data attribute again via jQuery will return you the previous object, because jQuery isn't detecting the change.

IMO this is a somewhat subtle issue-prone logic and it was more important to fix it rather than to align with it.

> The comment from your doc is a little misleading because Objects ARE updated (since storing the object, not json version) and only apply to simple values and using dataset() api.

I'm saying jQuery is caching retrieved values, i.e. it isn't retrieving them again, which is what it does, and I'm also mentioning using the `dataset` API, not mutating the cached object.

> Also second comment is incorrect - you only store in dataset if present, not data-XYZ

Updating the dataset object also adds the `data-*` attribute. I'm saying Cash will add the `data-*` attribute, wether it does it using `setAttribute` or via the `dataset` API it's an implementation detail.

> Is this lib being used by React ? any reason you did break behavior from jquery because that means we can't use to store Obj as well...

Yes I'm using it in [Notable](https://github.com/notable/notable), I don't know what projects others are using Cash for.

--- 

The "issue" here is that you're mutating the object, generally mutations should be avoided as they will lead to bugs such as this one, in your case though you can: 

1. Mutate the object and then setting it again via `$.fn.data`.
2. Cache it manually into your DOM node if that's what you want, just by doing `$('#foo')[0]['__myProp'] = myObj` or something.

**Comment by adumesny** [comment]
ok thanks, yeah I can use #2 to store into a custom field for internal use (and likely what I'll try), but existing external usage would break - though the plan is to remove JQuery entirely in which case some API will change (no JQuery objects returned or calls...). For now I can use a local cooy that only store Object by reference for temporary internal conversion...

**Comment by fabiospampinato** [comment]
Cash's goal isn't to be a drop-in replacement for jQuery, as that would require rewriting the entirety of jQuery. If you can find any issue that would prevent your library from becoming compatible with both jQuery and Cash feel free to let me know.

**Comment by adumesny** [comment]
thanks, I'll be using my mod version (if we can remove other JQ dependencies first). 
If it's not a drop in replacement (for the most often used JQ calls) then what is it ?

**Comment by fabiospampinato** [comment]
It's:

> An absurdly small jQuery alternative for modern browsers

Most things are drop-in replacements, but not all things.
