### ISSUE TITLE
Triggering `focusout`/`focusin` executes event handlers for `blur`/`focus`

### ISSUE THREAD

**Issue by PetarMax** [kenwheeler/cash#318]
I've noticed that the following combinations of `on`-`trigger` result in the corresponding handlers being executed:

`.on('blur', ...)` --- `.trigger('focusout')`
`.on('focus', ...)` --- `.trigger('focusin')`

Is this behaviour intended? This is not what happens in jQuery, where these two combinations do not execute the handlers. You can observe this by running the following:

```<!DOCTYPE html>
<html>
<head>
<title>Try jQuery Online</title>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script>

var counter = 0;

$(document).ready(function() {

    $("#myid").on('blur', function(){
        counter++;
    
        $("#myid").text(counter);
    });

    $("#addMe").click(function(){
        $("#myid").trigger('focusout');
    });
});
</script>

</head>
<body>
<p tabindex="0" id="myid">Counter</p>
<button id="addMe">Add 1</button>
</body>
</html>
```

using [this jQuery online editor](https://www.tutorialspoint.com/online_jquery_editor.php). Clicking on the add button will not add to the counter, but blurring the counter paragraph will.

On the other hand, the `eventsHover`-related events behave in the same way: the combinations

`.on('mouseenter', ...)` --- `.trigger('mouseover')`
`.on('mouseleave', ...)` --- `.trigger('mouseout')`

cause the handlers to be executed both in jQuery and cash.

**Comment by fabiospampinato** [comment]
This is a result of the way we're handling events, `blur` doesn't bubble so we are simply listening for `focusout` instead, leading to this misbehavior.

jQuery doesn't have this issue because I believe they have more tight control over their entire event system, we are just very lightly building on top of what the browser already provides.

I'm labeling this as a "bug" because it is one, but also as "wontfix" as it seems pretty harmless and fixing it might not be possible without sacrificing a lot of what Cash's goal is (i.e. being "An absurdly small jQuery alternative for modern browsers").

**Comment by paulabianca** [comment]
Maybe I'm missing something, but instead of `mouseenter` and `mouseleave`, Cash adds the `mouseover` and `mouseout` events to the dom. Is there a reason behind that? The native behavior of these events is slightly different and it would be great to be able to access the `mouseenter` and `mouseleave` events as well. jQuery docs actually encourage devs to use `mouseenter` and `mouseleave` instead of `mouseover` and `mouseout` and they make a good point. So, is there a chance to make this happen? I'm open to contributing to this.

**Comment by fabiospampinato** [comment]
@paulabianca For the same reason why we are listening for `focusout` rather than `blur`, `mouseenter` doesn't bubble and `mouseover` does.

I don't think this can really be fixed without rewriting large portions of the event system, like I think jQuery in order to fix this uses some custom propagation logic and synthetic events.

As I'm understanding it `mouseenter` and `mouseover` behave differently, i.e. they are not aliases of one another, but they can be used pretty interchangeably as the differences are basically only about the bubbling vs non-bubbling behavior.

**Comment by fabiospampinato** [comment]
This issue with non-bubbling native events (focus, blur, mouseenter, mouseleave) should now be fixed in Cash v7, turns out it was possible to fix this with a relatively small amount of changes, and our usage of the bubbling equivalents of those events created other issues as well.

**Comment by ijcd** [comment]
Not sure if this is related or expected, but when triggering an event on 7.0.3 (in jest, using jsdom) I'm seeing something similar:

`$('button#theButton').trigger('mouseenter')`

Leading to this event:

```
      {
        element: 'BUTTON',
        type: 'mouseover',
        meta: 'mouseenter.mynamespace',
        attrs: undefined,
        id: 'theButton',
        instance_id: undefined,
        component_id: undefined
      }
```

**Comment by fabiospampinato** [comment]
@ijcd yeah that's expected, we trigger `mouseover` instead so that it bubbles. If you are interacting with these events only through cash you shouldn't be able to really see any difference in practice.
