### ISSUE TITLE
Cannot read property 'insertBefore' of null

### ISSUE THREAD

**Issue by limonte** [kenwheeler/cash#324]
After upgrading to v6, I'm getting this error from production

```
Cannot read property 'insertBefore' of null
```

Unfortunately, this is all the info I can provide:

![image](https://user-images.githubusercontent.com/6059356/71923148-0743e680-3195-11ea-800a-d013ad2c0757.png)

I can't reproduce the issue by myself.

**Comment by limonte** [comment]
Firefox seems to be reporting another error:

```
t.parentNode is null
```

![image](https://user-images.githubusercontent.com/6059356/71923280-6275d900-3195-11ea-9b49-08e340c5139d.png)

**Comment by fabiospampinato** [comment]
The issue seems that you're calling a method that needs to fetch the parent node of an element, and if that element has been constructed via `parseHTML`, or it has been detached from the DOM, and it's a root node, then it doesn't have a parent node. 

jQuery kind of smooths over this I think, but not for all root nodes constructed via `parseHTML` (https://github.com/jquery/jquery/issues/4580) and I guess not for detached nodes either.

I don't think since cash v3 this behavior changed though so it's strange that you're only now seeing these errors 🤔 I'll have a closer look at this.

**Comment by limonte** [comment]
> I don't think since cash v3 this behavior changed though so it's strange that you're only now seeing these errors thinking I'll have a closer look at this.

For now I rolled back to v4. Thanks for taking a look at this!

**Comment by fabiospampinato** [comment]
I think the issue is this line: https://github.com/kenwheeler/cash/blob/dca2db7fe8c1b5b0b2b131c6ace151ebb0169c20/src/manipulation/insert_before.ts#L16

In v4 we were checking (sometimes?) if the parent node actually existed, while in v6 we assume it's there: https://github.com/kenwheeler/cash/blob/master/src/manipulation/helpers/insert_element.ts/#L12

Now in v4 you won't see an error about this, but the method isn't doing what you want it to do either, so I'd argue if in v4 the feature didn't work anyways it'd be better to switch to v6, if it did work then you may not need to call `replaceWith` there and that problematic line of code should be rewritten.

If the `word` variable points to a detached node, or to some HTML which will be evaluated as some detached nodes, which I believe is what is causing the error here, then I don't see any reason to call `replaceWith` on it 🤔

So I think the problem is more with that line of code than with cash itself. We could smooth some of this out like jQuery is doing, but even they aren't smoothing it out completely, so I've decided to leave things as they are for now in this regard.

Thoughts?

**Comment by limonte** [comment]
With your help, I was able to find the problematic code and fix it. Weird enough, I still can't reproduce the issue itself, whatever I put into the `word` variable, `$(word).replaceWith('something')` doesn't produce an exception.

Thank you for your help, feel free to close the issue.

**Comment by fabiospampinato** [comment]
These trigger the error:

```
$('<div>').replaceWith ( '<span>' )
$(document).replaceWith ( '<span>' )
```
