### ISSUE TITLE
The comparison against jQuery is inaccurate

### ISSUE THREAD

**Issue by mgol** [kenwheeler/cash#328]
### Current behavior

README, in the [Comparison section](https://github.com/kenwheeler/cash/blob/master/README.md#comparison) claims jQuery doesn't support partial builds. It also contains comparisons against the full jQuery 3.4.1 build.

### Expected behavior

jQuery has supported custom builds for a long time. See e.g. the [modules section of jQuery 3.4.1 README](https://github.com/jquery/jquery/blob/3.4.1/README.md#modules).

I don't know what exactly does Cash's "can exclude single files" ability means as [the documentation](https://github.com/kenwheeler/cash/blob/master/docs/partial_builds.md) doesn't expand a lot on that but in jQuery you can also exclude some individual files (see the ones mentioned in README). If you try to exclude some necessary low-level utils, though, the result might not be what you expect.

Also, as far as I understand, Cash doesn't support an equivalent of the ajax or effects jQuery modules so it'd be more fair to compare the sizes against the jQuery slim build - a custom build which excludes those modules as well. jQuery 4 will additionally exclude deferreds & callbacks modules but I think Cash doesn't implement them either. The slim build is present in the `jquery` npm package and on the CDNs as well, see e.g. the relevant files for jQuery 3.4.1 on the Google CDN:
https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.slim.js
https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.slim.min.js

See above. This is a report against README contents so the usual issue template doesn't make that much sense

**Comment by fabiospampinato** [comment]
Thanks for reporting the issues, the comparison table was written sloppily in hindsight.

> I don't know what exactly does Cash's "can exclude single files" ability means as the documentation  doesn't expand a lot on that but in jQuery you can also exclude some individual files (see the ones mentioned in README). If you try to exclude some necessary low-level utils, though, the result might not be what you expect.

I think we mean the same exact thing. I've updated that row of the comparison table, it should be clearer and fairer now. Basically the difference is that Cash uses a separate file for each method, for most methods, so you can exclude methods one by one.

Our docs about this, or what resemblance of them we have right now, should definitely be improved.

> Also, as far as I understand, Cash doesn't support an equivalent of the ajax or effects jQuery modules so it'd be more fair to compare the sizes against the jQuery slim build - a custom build which excludes those modules as well.

Fair enough, updated.

> jQuery 4 will additionally exclude deferreds & callbacks modules but I think Cash doesn't implement them either.

I'll make sure to add jQuery 4 to the comparison table once it's out. 

Cash doesn't implement everything that jQuery implements, so in some sense the size comparison will always be unfair, but I think it's still useful for new people discovering the library. 

Maybe I should make a list of all the features implemented in jQuery but not implemented in Cash, so far I haven't, both because listing what Cash implements implicitly tells you what it doesn't implement, and because writing such list I think would be pretty tedious.

---

I've also made the following changes:

- I've added a "Supports Older Browsers" row to the comparison table, as this is an important feature of jQuery.

- I've renamed the "Modern Codebase" row, which who knows what modern means, to "Typed Codebase", which should be clearer and fairer.

Sorry for the unfairness.
