### ISSUE TITLE
update npm

### ISSUE THREAD

**Issue by gebrits** [kenwheeler/cash#73]
Would appreciate a new release plus update to npm. Missing loads of useful stuff. E.g. `offset`

**Comment by hultberg** [comment]
`offset` is a function that is not yet requested in issues, perhaps open one if you would like the feature?

**Comment by gebrits** [comment]
Seems to be added 18 days ago? https://github.com/kenwheeler/cash/blob/3cb498ca7c5776b8cadcce5884f18e93a61931a9/src/offset.js#L13 ?

**Comment by simbo** [comment]
Version 1.1.0 was merged with [PR#70](kenwheeler/cash#70), with lots of fixes.

1.1.0 is not released on npm and as there is no version tag or release on github, that version is also not on bower, although package.json and bower.json are bumped to 1.1.0.

I've used the pr version before and since more than two weeks the github master version. Using a properly released version as dependency would be nice...

Are there any issues, why this should not be released yet?

Or do you need help setting up ci? (travis.yml is empty since two years)

**Comment by kenwheeler** [comment]
Because I'm the worst

**Comment by kenwheeler** [comment]
Seriously though, I need to get CI set up and find some time to give it the hand test prior to a release. I've been traveling the last month, and have had launches hitting, so I've haven't gotten to it.

**Comment by simbo** [comment]
Quick fix for this issue would be just adding a version tag for bower and do an `npm publish` in your local project folder.
This should be possible in a few minutes. Then you can go on travelling and setup ci for the next version...

**Comment by shshaw** [comment]
It looks like @kenwheeler did get the NPM entry updated: https://www.npmjs.com/package/cash-dom
